import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const config = JSON.parse(
  await readFile(new URL('../../renovate.json', import.meta.url), 'utf8'),
)

function rule(description) {
  const match = config.packageRules.find((candidate) => candidate.description === description)
  assert.ok(match, `missing Renovate rule: ${description}`)
  return match
}

test('ordinary updates explicitly match missing vulnerability metadata and reject breaking changes', () => {
  const ordinary = rule('Accumulate all ordinary non-breaking updates in one weekly release PR')

  assert.deepEqual(ordinary.matchJsonata, [
    '$not(isVulnerabilityAlert = true) and isBreaking != true',
  ])
  assert.equal(ordinary.automerge, true)
  assert.ok(ordinary.labels.includes('release:weekly'))
})

test('workflow action updates use the same ordinary-update guard', () => {
  const actions = rule(
    'Non-breaking workflow action updates are trusted only when generated by Renovate and fully accepted',
  )

  assert.deepEqual(actions.matchJsonata, [
    '$not(isVulnerabilityAlert = true) and isBreaking != true',
  ])
  assert.equal(actions.automerge, true)
  assert.ok(actions.addLabels.includes('review:automation'))
})

test('all breaking classifications require roadmap review regardless of update type', () => {
  const breaking = rule(
    'Every update Renovate classifies as breaking requires roadmap analysis and never automerges',
  )

  assert.deepEqual(breaking.matchJsonata, ['isBreaking = true'])
  assert.equal(breaking.matchUpdateTypes, undefined)
  assert.equal(breaking.automerge, false)
  assert.ok(breaking.labels.includes('roadmap:required'))
})

test('breaking High and Critical security updates retain severity while blocking automerge', () => {
  for (const severity of ['High', 'Critical']) {
    const breaking = rule(
      `Breaking ${severity} security fixes retain urgent identity but require manual impact review`,
    )

    assert.equal(breaking.automerge, false)
    assert.ok(breaking.labels.includes('roadmap:required'))
    assert.ok(breaking.labels.includes(`security:${severity.toLowerCase()}`))
    assert.match(breaking.matchJsonata[0], /isBreaking = true/)
  }
})
